version: '3.9'

services:

  postgres:
    image: postgres:17
    container_name: veiculos_postgres
    restart: always
    environment:
      POSTGRES_DB: veiculosdb
      POSTGRES_USER: veiculos
      POSTGRES_PASSWORD: veiculos123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - veiculos-net

  redis:
    image: redis:7
    container_name: veiculos_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - veiculos-net

networks:
  veiculos-net:

volumes:
  postgres_data:
  redis_data:
